In [1]:
import numpy as np
import pandas as pd

In [2]:
df_2021 = pd.read_csv('world-happiness-report-2021.csv')
df_history = pd.read_csv('world-happiness-report.csv')

In [3]:
df_2021.columns

Index(['Country name', 'Regional indicator', 'Ladder score',
       'Standard error of ladder score', 'upperwhisker', 'lowerwhisker',
       'Logged GDP per capita', 'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Ladder score in Dystopia',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia + residual'],
      dtype='object')

In [4]:
df_history.columns

Index(['Country name', 'year', 'Life Ladder', 'Log GDP per capita',
       'Social support', 'Healthy life expectancy at birth',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Positive affect', 'Negative affect'],
      dtype='object')

In [5]:
df1_2021= df_2021[['Country name','Regional indicator','Ladder score','Logged GDP per capita','Social support','Healthy life expectancy','Freedom to make life choices','Generosity','Perceptions of corruption']].copy()

In [6]:
df_history.head(1)

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,Afghanistan,2008,3.724,7.37,0.451,50.8,0.718,0.168,0.882,0.518,0.258

In [7]:
history_df= df_history[['Country name', 'year', 'Life Ladder', 'Log GDP per capita',
       'Social support', 'Healthy life expectancy at birth',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption']].copy()

In [8]:
df1_2021.head(1)

,Country name,Regional indicator,Ladder score,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,Finland,Western Europe,7.842,10.775,0.954,72.0,0.949,-0.098,0.186

In [9]:
history_df.head(1)

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption
0,Afghanistan,2008,3.724,7.37,0.451,50.8,0.718,0.168,0.882

In [10]:
df1_2021.rename(columns={'Ladder score':'Life Ladder', 'Logged GDP per capita':'Log GDP per capita','Healthy life expectancy':'Healthy life expectancy at birth'},inplace=True)

In [11]:
df1_2021['year']=2021

In [12]:
df1_2021.head(1)

,Country name,Regional indicator,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,year
0,Finland,Western Europe,7.842,10.775,0.954,72.0,0.949,-0.098,0.186,2021

In [13]:
df1_2021['Regional indicator'].value_counts()

Sub-Saharan Africa                    36
Western Europe                        21
Latin America and Caribbean           20
Middle East and North Africa          17
Central and Eastern Europe            17
Commonwealth of Independent States    12
Southeast Asia                         9
South Asia                             7
East Asia                              6
North America and ANZ                  4
Name: Regional indicator, dtype: int64

In [17]:
#df_north = df1_2021[df1_2021['Regional indicator']=='North America and ANZ']
df_north['Country name'].to_list()
#df_north

['New Zealand', 'Australia', 'Canada', 'United States']

In [18]:
def region(country):
    if country in ['Mauritius','Congo (Brazzaville)','Ivory Coast','Cameroon','Senegal','Ghana','Niger','Gambia','Benin','Guinea','South Africa','Gabon','Burkina Faso','Mozambique','Nigeria','Mali','Uganda','Liberia','Kenya','Namibia','Chad','Swaziland','Comoros','Ethiopia','Mauritania','Madagascar','Togo','Zambia', 'Sierra Leone','Burundi','Tanzania','Malawi','Lesotho','Botswana','Rwanda','Zimbabwe']:
        return 'Sub-Saharan Africa'
    elif country in ['Finland','Denmark','Switzerland','Iceland','Netherlands','Norway','Sweden','Luxembourg','Austria','Germany','Ireland','United Kingdom','Belgium','France','Malta','Spain','Italy','Cyprus','Portugal','Greece','North Cyprus']:
        return 'Western Europe'
    elif country in ['Costa Rica','Guatemala','Uruguay','Brazil','Mexico','Jamaica','Panama','Chile','El Salvador','Colombia','Nicaragua','Argentina','Honduras','Peru','Ecuador','Bolivia','Paraguay','Dominican Republic','Venezuela','Haiti']:
        return 'Latin America and Caribbean'
    elif country in ['Israel','Bahrain','United Arab Emirates','Saudi Arabia','Kuwait','Libya','Turkey','Morocco','Algeria','Iraq','Iran','Tunisia','Lebanon','Palestinian Territories','Jordan','Egypt','Yemen']:
        return 'Middle East and North Africa'
    elif country in ['Czech Republic','Slovenia','Kosovo','Slovakia','Lithuania','Estonia','Poland','Romania','Serbia','Latvia','Hungary','Croatia','Bosnia and Herzegovina','Montenegro', 'Bulgaria','Albania','North Macedonia']:
        return 'Central and Eastern Europe'
    elif country in ['Uzbekistan','Kazakhstan','Moldova','Kyrgyzstan','Belarus','Russia','Tajikistan','Armenia','Azerbaijan','Turkmenistan','Georgia','Ukraine']:
        return 'Commonwealth of Independent States'
    elif country in ['Singapore','Thailand','Philippines','Vietnam','Malaysia','Indonesia','Laos','Cambodia','Myanmar']:
        return 'Southeast Asia'
    elif country in ['Nepal','Maldives','Bangladesh','Pakistan','Sri Lanka','India','Afghanistan']:
        return 'South Asia'
    elif country in ['Taiwan Province of China','Japan','South Korea','Mongolia','Hong Kong S.A.R. of China','China']:
        return 'East Asia'
    elif country in ['New Zealand', 'Australia', 'Canada', 'United States']:
        return 'North America and ANZ'

In [19]:
history_df['Regional indicator']=history_df['Country name'].apply(region)
history_df

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Regional indicator
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,South Asia
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,South Asia
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,South Asia
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,South Asia
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,South Asia
...,...,...,...,...,...,...,...,...,...,...
1944,Zimbabwe,2016,3.735,7.984,0.768,54.40,0.733,-0.095,0.724,Sub-Saharan Africa
1945,Zimbabwe,2017,3.638,8.016,0.754,55.00,0.753,-0.098,0.751,Sub-Saharan Africa
1946,Zimbabwe,2018,3.616,8.049,0.775,55.60,0.763,-0.068,0.844,Sub-Saharan Africa
1947,Zimbabwe,2019,2.694,7.950,0.759,56.20,0.632,-0.064,0.831,Sub-Saharan Africa
1948,Zimbabwe,2020,3.160,7.829,0.717,56.80,0.643,-0.009,0.789,Sub-Saharan Africa

In [20]:
df1_2021['Regional indicator'].value_counts()

Sub-Saharan Africa                    36
Western Europe                        21
Latin America and Caribbean           20
Middle East and North Africa          17
Central and Eastern Europe            17
Commonwealth of Independent States    12
Southeast Asia                         9
South Asia                             7
East Asia                              6
North America and ANZ                  4
Name: Regional indicator, dtype: int64

In [21]:
df_sub_saharan=df1_2021[df1_2021['Regional indicator']=='Sub-Saharan Africa']

In [22]:
df_west=df1_2021[df1_2021['Regional indicator']=='Western Europe']

In [23]:
df_latin=df1_2021[df1_2021['Regional indicator']=='Latin America and Caribbean']

In [24]:
df_middle_east=df1_2021[df1_2021['Regional indicator']=='Middle East and North Africa']

In [25]:
df_central=df1_2021[df1_2021['Regional indicator']=='Central and Eastern Europe']

In [26]:
df_commonwealth=df1_2021[df1_2021['Regional indicator']=='Commonwealth of Independent States']

In [27]:
df_Southeast=df1_2021[df1_2021['Regional indicator']=='Southeast Asia']

In [28]:
df_South=df1_2021[df1_2021['Regional indicator']=='South Asia']

In [29]:
df_East=df1_2021[df1_2021['Regional indicator']=='East Asia']

In [30]:
df_north = df1_2021[df1_2021['Regional indicator']=='North America and ANZ']

In [31]:
history_df = history_df.append([df_sub_saharan,df_west,df_latin,df_middle_east,df_central,df_commonwealth,df_Southeast,df_South,df_East,df_north],ignore_index=True)

In [32]:
history_df

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Regional indicator
0,Afghanistan,2008,3.724,7.370,0.451,50.800,0.718,0.168,0.882,South Asia
1,Afghanistan,2009,4.402,7.540,0.552,51.200,0.679,0.190,0.850,South Asia
2,Afghanistan,2010,4.758,7.647,0.539,51.600,0.600,0.121,0.707,South Asia
3,Afghanistan,2011,3.832,7.620,0.521,51.920,0.496,0.162,0.731,South Asia
4,Afghanistan,2012,3.783,7.705,0.521,52.240,0.531,0.236,0.776,South Asia
...,...,...,...,...,...,...,...,...,...,...
2093,China,2021,5.339,9.673,0.811,69.593,0.904,-0.146,0.755,East Asia
2094,New Zealand,2021,7.277,10.643,0.948,73.400,0.929,0.134,0.242,North America and ANZ
2095,Australia,2021,7.183,10.796,0.940,73.900,0.914,0.159,0.442,North America and ANZ
2096,Canada,2021,7.103,10.776,0.926,73.800,0.915,0.089,0.415,North America and ANZ
2097,United States,2021,6.951,11.023,0.920,68.200,0.837,0.098,0.698,North America and ANZ

In [34]:
history_df[history_df['Regional indicator']=='Sub-Saharan Africa'].groupby('Country name')

In [35]:
history_df[history_df['Regional indicator']=='Sub-Saharan Africa'].groupby('Country name')[['Life Ladder','Freedom to make life choices','Perceptions of corruption']].describe()

                    Life Ladder                                              \
                          count      mean       std    min      25%     50%
Country name
Benin                      13.0  4.124615  0.822378  3.193  3.47900  3.8700
Botswana                   13.0  3.955615  0.656981  3.461  3.49900  3.5530
Burkina Faso               14.0  4.215786  0.518539  3.326  3.87325  4.1210
Burundi                     6.0  3.586000  0.344258  2.905  3.59875  3.7405
Cameroon                   16.0  4.654813  0.431192  3.851  4.28675  4.6475
Chad                       15.0  4.065800  0.414214  3.435  3.69100  4.1410
Comoros                     7.0  3.993286  0.363528  3.476  3.82500  3.9560
Congo (Brazzaville)        11.0  4.545364  0.616289  3.820  4.00550  4.5100
Ethiopia                   10.0  4.386700  0.168202  4.100  4.28075  4.4120
Gabon                      10.0  4.476900  0.441368  3.800  4.04275  4.7215
Gambia                      4.0  4.813750  0.474253  4.118  4.72100  4.9865
Ghana                      16.0  4.835812  0.510756  3.860  4.52975  4.9660
Guinea                     10.0  4.199700  0.696959  3.412  3.61525  3.9735
Ivory Coast                10.0  4.675500  0.677440  3.570  4.25900  4.7905
Kenya                      16.0  4.415687  0.267385  3.795  4.26650  4.4405
Lesotho                     5.0  3.905000  0.573685  3.512  3.51200  3.7950
Liberia                    10.0  4.105100  0.694289  2.702  3.80950  4.2085
Madagascar                 12.0  3.999750  0.349581  3.551  3.67275  4.0255
Malawi                     13.0  4.019769  0.561681  3.335  3.60000  3.8690
Mali                       14.0  4.283286  0.407338  3.676  3.98625  4.2140
Mauritania                 14.0  4.398286  0.264985  3.923  4.20600  4.3930
Mauritius                   8.0  5.887000  0.280888  5.477  5.63850  5.9485
Mozambique                  9.0  4.695889  0.214416  4.280  4.59500  4.6540
Namibia                     7.0  4.599429  0.188096  4.436  4.44600  4.5740
Niger                      15.0  4.308867  0.490974  3.671  3.94950  4.2360
Nigeria                    14.0  4.995357  0.325777  4.356  4.77450  4.9360
Rwanda                     13.0  3.636000  0.401842  3.108  3.33300  3.4830
Senegal                    15.0  4.487800  0.499501  3.647  4.35350  4.5950
Sierra Leone               13.0  4.091846  0.561622  2.997  3.62800  4.1340
South Africa               16.0  4.878188  0.388683  3.661  4.81350  4.9390
Swaziland                   4.0  4.445750  0.290712  4.212  4.28400  4.3520
Tanzania                   16.0  3.692687  0.396172  2.903  3.43575  3.6505
Togo                       10.0  3.610200  0.601946  2.808  3.00250  3.8235
Uganda                     16.0  4.324875  0.380263  3.710  4.14500  4.3155
Zambia                     15.0  4.519800  0.564660  3.307  4.05700  4.7300
Zimbabwe                   16.0  3.836500  0.682563  2.694  3.25350  3.7190

                                    Freedom to make life choices            \
                         75%    max                        count      mean
Country name
Benin                4.85300  5.820                         13.0  0.742538
Botswana             4.12800  5.451                         13.0  0.821462
Burkina Faso         4.71750  4.927                         14.0  0.655643
Burundi              3.77500  3.792                          6.0  0.480000
Cameroon             5.04700  5.251                         16.0  0.734000
Chad                 4.37400  4.632                         15.0  0.504800
Comoros              4.13100  4.609                          7.0  0.531000
Congo (Brazzaville)  5.04850  5.490                         11.0  0.720545
Ethiopia             4.53850  4.573                         10.0  0.745600
Gabon                4.81975  4.914                         10.0  0.683500
Gambia               5.07925  5.164                          4.0  0.726250
Ghana                5.12100  5.608                         16.0  0.803063
Guinea               4.84750  5.252                         10.0  0.706900
Ivory Coast          5.26525  5.392                         10.0  0.754100
Kenya                4.58375  4.905                         16.0  0.724000
Lesotho              3.80800  4.898                          5.0  0.707000
Liberia              4.53425  5.121                         10.0  0.729700
Madagascar           4.24075  4.640                         11.0  0.519273
Malawi               4.27900  5.148                         13.0  0.789769
Mali                 4.64575  4.988                         14.0  0.676000
Mauritania           4.62975  4.785                         14.0  0.556571
Mauritius            6.08025  6.241                          8.0  0.859125
Mozambique           4.83300  4.971                          9.0  0.751667
Namibia              4.70400  4.886                          7.0  0.759714
Niger                4.58600  5.164                         15.0  0.749933
Nigeria              5.24400  5.503                         14.0  0.679786
Rwanda               4.03000  4.363                         13.0  0.870154
Senegal              4.68300  5.489                         15.0  0.683400
Sierra Leone         4.50200  4.909                         13.0  0.706077
South Africa         5.09650  5.346                         16.0  0.744938
Swaziland            4.51375  4.867                          4.0  0.640250
Tanzania             3.94325  4.385                         16.0  0.721500
Togo                 4.08600  4.361                         10.0  0.622900
Uganda               4.61800  4.948                         16.0  0.729437
Zambia               4.92100  5.260                         15.0  0.758467
Zimbabwe             4.30850  4.955                         16.0  0.593500

                     ...                 Perceptions of corruption            \
                     ...      75%    max                     count      mean
Country name         ...
Benin                ...  0.77600  0.783                      13.0  0.774923
Botswana             ...  0.83300  0.858                      13.0  0.783462
Burkina Faso         ...  0.70625  0.741                      14.0  0.761357
Burundi              ...  0.59200  0.646                       6.0  0.711500
Cameroon             ...  0.79250  0.817                      16.0  0.876875
Chad                 ...  0.56500  0.650                      15.0  0.866267
Comoros              ...  0.54300  0.560                       7.0  0.757000
Congo (Brazzaville)  ...  0.77550  0.850                      10.0  0.781100
Ethiopia             ...  0.76525  0.803                       9.0  0.728333
Gabon                ...  0.72800  0.772                      10.0  0.828400
Gambia               ...  0.74225  0.812                       4.0  0.701750
Ghana                ...  0.84975  0.891                      16.0  0.860625
Guinea               ...  0.72975  0.797                      10.0  0.767200
Ivory Coast          ...  0.76975  0.800                      10.0  0.769700
Kenya                ...  0.79925  0.853                      16.0  0.861125
Lesotho              ...  0.72900  0.757                       5.0  0.827600
Liberia              ...  0.76525  0.819                      10.0  0.852000
Madagascar           ...  0.55150  0.570                      11.0  0.833364
Malawi               ...  0.81000  0.910                      13.0  0.772692
Mali                 ...  0.72875  0.823                      14.0  0.801857
Mauritania           ...  0.60050  0.735                      14.0  0.731429
Mauritius            ...  0.87350  0.912                       8.0  0.823875
Mozambique           ...  0.87000  0.897                       9.0  0.729556
Namibia              ...  0.79550  0.849                       7.0  0.834571
Niger                ...  0.81150  0.880                      15.0  0.684000
Nigeria              ...  0.73500  0.826                      14.0  0.893286
Rwanda               ...  0.90800  0.924                      13.0  0.184538
Senegal              ...  0.72800  0.777                      15.0  0.821667
Sierra Leone         ...  0.72000  0.770                      13.0  0.856154
South Africa         ...  0.77725  0.862                      15.0  0.844067
Swaziland            ...  0.66275  0.710                       4.0  0.760250
Tanzania             ...  0.80175  0.850                      16.0  0.755813
Togo                 ...  0.70350  0.772                      10.0  0.800100
Uganda               ...  0.76075  0.834                      16.0  0.845750
Zambia               ...  0.80100  0.823                      15.0  0.828467
Zimbabwe             ...  0.66950  0.763                      16.0  0.842750


                          std    min      25%     50%      75%    max
Country name
Benin                0.095977  0.532  0.74700  0.8060  0.84900  0.856
Botswana             0.043227  0.723  0.74300  0.8010  0.81400  0.860
Burkina Faso         0.053212  0.693  0.72625  0.7525  0.79025  0.887
Burundi              0.105994  0.599  0.62450  0.6975  0.78550  0.860
Cameroon             0.033878  0.817  0.85400  0.8725  0.90025  0.945
Chad                 0.055891  0.763  0.82600  0.8760  0.88650  0.961
Comoros              0.058663  0.651  0.73650  0.7620  0.78750  0.838
Congo (Brazzaville)  0.038564  0.738  0.74675  0.7765  0.80600  0.841
Ethiopia             0.068764  0.567  0.70300  0.7500  0.76100  0.799
Gabon                0.031634  0.780  0.81175  0.8315  0.84975  0.868
Gambia               0.096907  0.572  0.66125  0.7185  0.75900  0.798
Ghana                0.044764  0.771  0.84425  0.8600  0.89100  0.945
Guinea               0.032155  0.705  0.75150  0.7640  0.79000  0.815
Ivory Coast          0.063437  0.671  0.74725  0.7740  0.79325  0.902
Kenya                0.041986  0.794  0.83475  0.8535  0.90950  0.923
Lesotho              0.082041  0.743  0.76800  0.7970  0.91500  0.915
Liberia              0.038626  0.776  0.83100  0.8585  0.86875  0.903
Madagascar           0.054654  0.720  0.79700  0.8540  0.86600  0.897
Malawi               0.076669  0.676  0.69100  0.7660  0.83500  0.886
Mali                 0.064700  0.658  0.76750  0.8055  0.84125  0.918
Mauritania           0.081375  0.586  0.70800  0.7290  0.76950  0.848
Mauritius            0.044280  0.772  0.78800  0.8140  0.85500  0.891
Mozambique           0.080688  0.632  0.68200  0.6910  0.75800  0.864
Namibia              0.028524  0.790  0.82050  0.8390  0.84650  0.879
Niger                0.100727  0.483  0.62100  0.7110  0.75200  0.814
Nigeria              0.025385  0.835  0.87425  0.9025  0.91250  0.926
Rwanda               0.096590  0.078  0.11700  0.1640  0.21400  0.410
Senegal              0.051672  0.700  0.79850  0.8250  0.85150  0.918
Sierra Leone         0.035534  0.786  0.83600  0.8560  0.86600  0.925
South Africa         0.035091  0.791  0.81950  0.8410  0.86250  0.912
Swaziland            0.105313  0.692  0.70400  0.7160  0.77225  0.917
Tanzania             0.139803  0.521  0.63975  0.7775  0.88025  0.930
Togo                 0.063243  0.726  0.74575  0.8020  0.82775  0.932
Uganda               0.027111  0.807  0.82450  0.8440  0.86025  0.898
Zambia               0.062383  0.732  0.79550  0.8110  0.87650  0.948
Zimbabwe             0.066040  0.724  0.81750  0.8305  0.87050  0.964

[36 rows x 24 columns]

In [36]:
history_df[history_df['Regional indicator']=='Middle East and North Africa'].groupby('Country name')[['Life Ladder','Freedom to make life choices','Perceptions of corruption']].describe()

                        Life Ladder                                      \
                              count      mean       std    min      25%
Country name
Algeria                         9.0  5.334000  0.470605  4.745  5.04300
Bahrain                        12.0  6.055500  0.648359  4.824  5.87800
Egypt                          16.0  4.514687  0.506052  3.559  4.19650
Iran                           14.0  4.854429  0.295549  4.278  4.69075
Iraq                           13.0  4.690385  0.188185  4.413  4.54200
Israel                         16.0  7.214562  0.167966  6.841  7.14550
Jordan                         16.0  5.164625  0.592731  4.094  4.76575
Kuwait                         12.0  6.259750  0.249567  5.947  6.10300
Lebanon                        15.0  4.955067  0.386486  4.024  4.62400
Libya                           7.0  5.526286  0.150502  5.330  5.42200
Morocco                        11.0  5.010545  0.272039  4.383  4.90750
Palestinian Territories        15.0  4.611600  0.191335  4.151  4.50000
Saudi Arabia                   16.0  6.535375  0.300876  6.148  6.33550
Tunisia                        13.0  4.743538  0.337608  4.124  4.52100
Turkey                         16.0  5.220437  0.296542  4.719  4.93300
United Arab Emirates           14.0  6.783357  0.248301  6.458  6.57700
Yemen                          13.0  3.892692  0.550441  2.983  3.65800

                                                Freedom to make life choices  \
                            50%      75%    max                        count
Country name
Algeria                  5.3170  5.46400  6.355                          7.0
Bahrain                  6.1675  6.33200  7.098                         11.0
Egypt                    4.5145  4.79350  5.541                         15.0
Iran                     4.7590  5.09825  5.336                         14.0
Iraq                     4.7250  4.78500  5.065                         12.0
Israel                   7.2280  7.33725  7.433                         16.0
Jordan                   5.2215  5.54675  6.295                         14.0
Kuwait                   6.1630  6.40350  6.798                         11.0
Lebanon                  5.1540  5.19700  5.491                         15.0
Libya                    5.4940  5.63100  5.754                          7.0
Morocco                  5.0570  5.15250  5.386                         11.0
Palestinian Territories  4.6470  4.71900  4.907                         15.0
Saudi Arabia             6.4840  6.59575  7.267                         15.0
Tunisia                  4.7410  5.02500  5.246                         13.0
Turkey                   5.2425  5.49600  5.623                         16.0
United Arab Emirates     6.7225  6.99575  7.218                         13.0
Yemen                    3.9680  4.21800  4.809                         13.0

                                   ...                  \
                             mean  ...      75%    max
Country name                       ...
Algeria                  0.513571  ...  0.58500  0.593
Bahrain                  0.867364  ...  0.90650  0.945
Egypt                    0.633333  ...  0.71550  0.817
Iran                     0.683000  ...  0.76625  0.798
Iraq                     0.530417  ...  0.63400  0.700
Israel                   0.728062  ...  0.77900  0.834
Jordan                   0.743214  ...  0.77000  0.788
Kuwait                   0.820545  ...  0.86700  0.934
Lebanon                  0.617867  ...  0.66100  0.703
Libya                    0.771714  ...  0.78000  0.822
Morocco                  0.730727  ...  0.79400  0.819
Palestinian Territories  0.544933  ...  0.64250  0.657
Saudi Arabia             0.731467  ...  0.83750  0.891
Tunisia                  0.625923  ...  0.65900  0.781
Turkey                   0.547625  ...  0.63425  0.653
United Arab Emirates     0.917308  ...  0.94200  0.962
Yemen                    0.620846  ...  0.65900  0.706

                        Perceptions of corruption                             \
                                            count      mean       std    min
Country name
Algeria                                       7.0  0.699714  0.055578  0.618
Bahrain                                       6.0  0.581500  0.115801  0.438
Egypt                                        10.0  0.823900  0.072278  0.684
Iran                                         14.0  0.716143  0.070859  0.636
Iraq                                         13.0  0.812077  0.064283  0.710
Israel                                       16.0  0.832250  0.062313  0.743
Jordan                                        5.0  0.697400  0.030778  0.664
Kuwait                                        5.0  0.557000  0.160823  0.328
Lebanon                                      15.0  0.909000  0.029199  0.853
Libya                                         5.0  0.692600  0.056871  0.646
Morocco                                      11.0  0.817727  0.053922  0.717
Palestinian Territories                      15.0  0.796600  0.038474  0.730
Saudi Arabia                                  4.0  0.535500  0.103165  0.445
Tunisia                                      13.0  0.838923  0.062400  0.722
Turkey                                       16.0  0.768437  0.062236  0.649
United Arab Emirates                          4.0  0.371500  0.160236  0.203
Yemen                                        10.0  0.822200  0.042705  0.754


                             25%     50%      75%    max
Country name
Algeria                  0.66400  0.7000  0.74650  0.759
Bahrain                  0.51075  0.5540  0.68200  0.722
Egypt                    0.79650  0.8220  0.87475  0.914
Iran                     0.67975  0.7065  0.71475  0.872
Iraq                     0.76200  0.7990  0.85900  0.910
Israel                   0.78425  0.8335  0.89275  0.923
Jordan                   0.67000  0.7050  0.70900  0.739
Kuwait                   0.48600  0.5600  0.67500  0.736
Lebanon                  0.89400  0.9110  0.93200  0.949
Libya                    0.66700  0.6730  0.68600  0.791
Morocco                  0.78600  0.8410  0.84400  0.900
Palestinian Territories  0.76350  0.8040  0.82500  0.858
Saudi Arabia             0.49000  0.5065  0.55200  0.684
Tunisia                  0.81100  0.8690  0.88600  0.913
Turkey                   0.74550  0.7750  0.80525  0.877
United Arab Emirates     0.30500  0.3470  0.41350  0.589
Yemen                    0.79425  0.8145  0.84775  0.885

[17 rows x 24 columns]

In [37]:
history_df[history_df['Regional indicator']=='South Asia'].groupby('Country name')[['Life Ladder','Freedom to make life choices','Perceptions of corruption']].describe()

             Life Ladder                                                      \
                   count      mean       std    min      25%    50%      75%
Country name
Afghanistan         13.0  3.512231  0.769187  2.375  2.69400  3.724  3.98300
Bangladesh          16.0  4.771375  0.292925  4.310  4.59425  4.692  5.03175
India               16.0  4.432313  0.551463  3.249  4.14575  4.426  4.78725
Maldives             2.0  5.198000  0.000000  5.198  5.19800  5.198  5.19800
Nepal               15.0  4.728133  0.417833  3.809  4.50400  4.748  4.94600
Pakistan            15.0  5.221933  0.433016  4.414  5.03300  5.225  5.51050
Sri Lanka           14.0  4.309643  0.150113  3.977  4.21600  4.328  4.40250

                    Freedom to make life choices            ...           \
                max                        count      mean  ...      75%
Country name                                                ...
Afghanistan   4.758                         13.0  0.507692  ...  0.57800
Bangladesh    5.280                         16.0  0.758750  ...  0.87550
India         5.348                         16.0  0.797813  ...  0.87850
Maldives      5.198                          2.0  0.854500  ...  0.85475
Nepal         5.449                         15.0  0.682733  ...  0.77600
Pakistan      5.831                         15.0  0.531000  ...  0.65950
Sri Lanka     4.612                         14.0  0.814929  ...  0.83925

                    Perceptions of corruption                             \
                max                     count      mean       std    min
Country name
Afghanistan   0.718                      13.0  0.849538  0.078708  0.707
Bangladesh    0.902                      16.0  0.738938  0.052984  0.635
India         0.906                      16.0  0.825063  0.050513  0.752
Maldives      0.855                       1.0  0.825000       NaN  0.825
Nepal         0.845                      15.0  0.845133  0.076942  0.712
Pakistan      0.773                      15.0  0.797733  0.058349  0.677
Sri Lanka     0.902                      14.0  0.821857  0.051300  0.690


                  25%    50%      75%    max
Country name
Afghanistan   0.79300  0.871  0.92400  0.954
Bangladesh    0.69775  0.750  0.77850  0.806
India         0.77900  0.831  0.86225  0.908
Maldives      0.82500  0.825  0.82500  0.825
Nepal         0.79350  0.877  0.89850  0.950
Pakistan      0.78150  0.794  0.84600  0.874
Sri Lanka     0.79900  0.843  0.85825  0.863

[7 rows x 24 columns]

In [38]:
history_df[history_df['Country name']=='India']

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Regional indicator
732,India,2006,5.348,8.145,0.707,55.720,0.774,NaN,0.855,South Asia
733,India,2007,5.027,8.204,0.569,56.140,0.729,-0.051,0.862,South Asia
734,India,2008,5.146,8.220,0.684,56.560,0.756,-0.072,0.891,South Asia
735,India,2009,4.522,8.281,0.653,56.980,0.679,-0.026,0.895,South Asia
736,India,2010,4.989,8.349,0.605,57.400,0.783,0.058,0.863,South Asia
737,India,2011,4.635,8.387,0.553,57.700,0.838,-0.038,0.908,South Asia
738,India,2012,4.720,8.428,0.511,58.000,0.609,0.067,0.830,South Asia
739,India,2013,4.428,8.478,0.553,58.300,0.740,0.084,0.832,South Asia
740,India,2014,4.424,8.538,0.621,58.600,0.809,-0.026,0.832,South Asia
741,India,2015,4.342,8.604,0.610,58.900,0.777,-0.005,0.776,South Asia
742,India,2016,4.179,8.673,0.614,59.300,0.820,0.046,0.765,South Asia
743,India,2017,4.046,8.730,0.607,59.700,0.886,-0.042,0.781,South Asia
744,India,2018,3.818,8.779,0.638,60.100,0.890,0.085,0.805,South Asia
745,India,2019,3.249,8.818,0.561,60.500,0.876,0.112,0.752,South Asia
746,India,2020,4.225,8.703,0.617,60.900,0.906,0.075,0.780,South Asia
2086,India,2021,3.819,8.755,0.603,60.633,0.893,0.089,0.774,South Asia

In [39]:
history_df[history_df['Country name']=='Burkina Faso']

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Regional indicator
245,Burkina Faso,2006,3.801,7.367,0.796,46.660,0.588,0.028,0.798,Sub-Saharan Africa
246,Burkina Faso,2007,4.017,7.377,0.771,47.420,0.582,-0.060,0.833,Sub-Saharan Africa
247,Burkina Faso,2008,3.846,7.403,0.727,48.180,0.612,-0.101,0.887,Sub-Saharan Africa
248,Burkina Faso,2010,4.036,7.453,0.773,49.700,0.587,-0.036,0.767,Sub-Saharan Africa
249,Burkina Faso,2011,4.785,7.487,0.710,50.240,0.725,-0.105,0.707,Sub-Saharan Africa
250,Burkina Faso,2012,3.955,7.520,0.744,50.780,0.622,-0.070,0.726,Sub-Saharan Africa
251,Burkina Faso,2013,3.326,7.546,0.745,51.320,0.741,-0.016,0.765,Sub-Saharan Africa
252,Burkina Faso,2014,3.481,7.559,0.742,51.860,0.710,-0.004,0.801,Sub-Saharan Africa
253,Burkina Faso,2015,4.419,7.568,0.705,52.400,0.659,0.004,0.693,Sub-Saharan Africa
254,Burkina Faso,2016,4.206,7.596,0.764,52.900,0.645,-0.001,0.721,Sub-Saharan Africa
255,Burkina Faso,2017,4.647,7.627,0.785,53.400,0.614,-0.063,0.727,Sub-Saharan Africa
256,Burkina Faso,2018,4.927,7.665,0.665,53.900,0.721,-0.013,0.757,Sub-Saharan Africa
257,Burkina Faso,2019,4.741,7.691,0.683,54.400,0.678,-0.004,0.729,Sub-Saharan Africa
1961,Burkina Faso,2021,4.834,7.678,0.672,54.151,0.695,-0.009,0.748,Sub-Saharan Africa

In [40]:
history_df[history_df['Country name']=='Egypt']

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Regional indicator
498,Egypt,2005,5.168,9.036,0.848,59.700,0.817,NaN,NaN,Middle East and North Africa
499,Egypt,2007,5.541,9.135,0.686,59.820,0.609,-0.121,NaN,Middle East and North Africa
500,Egypt,2008,4.632,9.186,0.738,59.880,NaN,-0.087,0.914,Middle East and North Africa
501,Egypt,2009,5.066,9.213,0.744,59.940,0.611,-0.100,0.801,Middle East and North Africa
502,Egypt,2010,4.669,9.244,0.769,60.000,0.486,-0.076,0.826,Middle East and North Africa
503,Egypt,2011,4.174,9.240,0.753,60.160,0.590,-0.151,0.859,Middle East and North Africa
504,Egypt,2012,4.204,9.240,0.737,60.320,0.452,-0.138,0.880,Middle East and North Africa
505,Egypt,2013,3.559,9.239,0.675,60.480,0.474,-0.141,0.913,Middle East and North Africa
506,Egypt,2014,4.885,9.245,0.619,60.640,0.578,-0.126,0.749,Middle East and North Africa
507,Egypt,2015,4.763,9.266,0.730,60.800,0.659,-0.089,0.684,Middle East and North Africa
508,Egypt,2016,4.557,9.287,0.809,61.100,0.656,-0.141,0.818,Middle East and North Africa
509,Egypt,2017,3.929,9.307,0.638,61.400,0.593,-0.152,NaN,Middle East and North Africa
510,Egypt,2018,4.005,9.338,0.759,61.700,0.682,-0.215,NaN,Middle East and North Africa
511,Egypt,2019,4.328,9.373,0.772,62.000,0.774,-0.199,NaN,Middle East and North Africa
512,Egypt,2020,4.472,9.383,0.673,62.300,0.770,-0.112,NaN,Middle East and North Africa
2041,Egypt,2021,4.283,9.367,0.750,61.998,0.749,-0.182,0.795,Middle East and North Africa

In [38]:
history_df.describe()

,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption
count,2098.000000,2098.000000,2062.000000,2085.000000,2043.000000,2066.000000,2009.000000,1988.000000
mean,2013.768827,5.471402,9.373060,0.812709,63.478503,0.746094,-0.001027,0.745650
std,4.486449,1.112676,1.154247,0.118203,7.468780,0.140766,0.161400,0.186261
min,2005.000000,2.375000,6.635000,0.290000,32.300000,0.258000,-0.335000,0.035000
25%,2010.000000,4.652250,8.470500,0.750000,58.704500,0.652000,-0.115000,0.688750
50%,2014.000000,5.392000,9.462000,0.835000,65.280000,0.767000,-0.027000,0.801000
75%,2018.000000,6.282500,10.360750,0.905000,68.660000,0.859000,0.089000,0.869000
max,2021.000000,8.019000,11.648000,0.987000,77.100000,0.985000,0.698000,0.983000

In [41]:
def trust(corrupt):
    if corrupt >= 0.869000:
        return 'Low trust in institutions'
    elif corrupt > 0.801000 and corrupt < 0.869000:
        return 'Lower than normal level trust in institutions'
    elif corrupt > 0.688750 and corrupt <= 0.801000:
        return 'About the normal level trust in institutions'
    else:
        return 'High level trust in institutions'

In [42]:
history_df['Trust in institutions'] = history_df['Perceptions of corruption'].apply(trust)
history_df

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Regional indicator,Trust in institutions
0,Afghanistan,2008,3.724,7.370,0.451,50.800,0.718,0.168,0.882,South Asia,Low trust in institutions
1,Afghanistan,2009,4.402,7.540,0.552,51.200,0.679,0.190,0.850,South Asia,Lower than normal level trust in institutions
2,Afghanistan,2010,4.758,7.647,0.539,51.600,0.600,0.121,0.707,South Asia,About the normal level trust in institutions
3,Afghanistan,2011,3.832,7.620,0.521,51.920,0.496,0.162,0.731,South Asia,About the normal level trust in institutions
4,Afghanistan,2012,3.783,7.705,0.521,52.240,0.531,0.236,0.776,South Asia,About the normal level trust in institutions
...,...,...,...,...,...,...,...,...,...,...,...
2093,China,2021,5.339,9.673,0.811,69.593,0.904,-0.146,0.755,East Asia,About the normal level trust in institutions
2094,New Zealand,2021,7.277,10.643,0.948,73.400,0.929,0.134,0.242,North America and ANZ,High level trust in institutions
2095,Australia,2021,7.183,10.796,0.940,73.900,0.914,0.159,0.442,North America and ANZ,High level trust in institutions
2096,Canada,2021,7.103,10.776,0.926,73.800,0.915,0.089,0.415,North America and ANZ,High level trust in institutions
2097,United States,2021,6.951,11.023,0.920,68.200,0.837,0.098,0.698,North America and ANZ,About the normal level trust in institutions

In [43]:
history_df[history_df['Country name']=='Pakistan'][['Country name','year','Perceptions of corruption','Trust in institutions']]

,Country name,year,Perceptions of corruption,Trust in institutions
1311,Pakistan,2005,0.844,Lower than normal level trust in institutions
1312,Pakistan,2007,0.794,About the normal level trust in institutions
1313,Pakistan,2008,0.848,Lower than normal level trust in institutions
1314,Pakistan,2009,0.874,Low trust in institutions
1315,Pakistan,2010,0.852,Lower than normal level trust in institutions
1316,Pakistan,2011,0.857,Lower than normal level trust in institutions
1317,Pakistan,2012,0.842,Lower than normal level trust in institutions
1318,Pakistan,2013,0.792,About the normal level trust in institutions
1319,Pakistan,2014,0.677,High level trust in institutions
1320,Pakistan,2015,0.717,About the normal level trust in institutions
1321,Pakistan,2016,0.793,About the normal level trust in institutions
1322,Pakistan,2017,0.714,About the normal level trust in institutions
1323,Pakistan,2018,0.799,About the normal level trust in institutions
1324,Pakistan,2019,0.776,About the normal level trust in institutions
2084,Pakistan,2021,0.787,About the normal level trust in institutions

In [44]:
history_df[history_df['Country name']=='South Africa'][['Country name','year','Perceptions of corruption','Trust in institutions']]

,Country name,year,Perceptions of corruption,Trust in institutions
1566,South Africa,2006,NaN,High level trust in institutions
1567,South Africa,2007,0.859,Lower than normal level trust in institutions
1568,South Africa,2008,0.866,Lower than normal level trust in institutions
1569,South Africa,2009,0.904,Low trust in institutions
1570,South Africa,2010,0.791,About the normal level trust in institutions
1571,South Africa,2011,0.819,Lower than normal level trust in institutions
1572,South Africa,2012,0.838,Lower than normal level trust in institutions
1573,South Africa,2013,0.800,About the normal level trust in institutions
1574,South Africa,2014,0.820,Lower than normal level trust in institutions
1575,South Africa,2015,0.853,Lower than normal level trust in institutions
1576,South Africa,2016,0.813,Lower than normal level trust in institutions
1577,South Africa,2017,0.865,Lower than normal level trust in institutions
1578,South Africa,2018,0.841,Lower than normal level trust in institutions
1579,South Africa,2019,0.820,Lower than normal level trust in institutions
1580,South Africa,2020,0.912,Low trust in institutions
1959,South Africa,2021,0.860,Lower than normal level trust in institutions

In [45]:
history_df[history_df['Country name']=='Lebanon'][['Country name','year','Perceptions of corruption','Trust in institutions']]

,Country name,year,Perceptions of corruption,Trust in institutions
968,Lebanon,2005,0.945,Low trust in institutions
969,Lebanon,2006,0.902,Low trust in institutions
970,Lebanon,2008,0.927,Low trust in institutions
971,Lebanon,2009,0.937,Low trust in institutions
972,Lebanon,2010,0.949,Low trust in institutions
973,Lebanon,2011,0.911,Low trust in institutions
974,Lebanon,2012,0.856,Lower than normal level trust in institutions
975,Lebanon,2013,0.921,Low trust in institutions
976,Lebanon,2014,0.939,Low trust in institutions
977,Lebanon,2015,0.889,Low trust in institutions
978,Lebanon,2016,0.853,Lower than normal level trust in institutions
979,Lebanon,2017,0.911,Low trust in institutions
980,Lebanon,2018,0.907,Low trust in institutions
981,Lebanon,2019,0.890,Low trust in institutions
2038,Lebanon,2021,0.898,Low trust in institutions